/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kidslearning;

import java.awt.Color;

/**
 *
 * @author welli
 */
public class QuestionAnswersGameFrame extends javax.swing.JFrame {
    
    private int frameWidth, frameHeight, answerWidth, answerHeight;
    private AnswersPanel answersPanel;
    private Question question;
    
    /**
     * Creates new form QuestionsAnswersFrame
     */
    public QuestionAnswersGameFrame() {
        initComponents();
        setParameters();
        setGameDimentions();
        initGame();
    }
    
    public void setParameters() {
        frameWidth = 800;
        frameHeight = 400;
        question = new Question();
        answersPanel = new AnswersPanel();
        this.setSize(frameWidth, frameHeight);
        this.setLayout(null);
    }
    
    public void setGameDimentions() {
        question.setPosX(20);
        question.setPosY(0);
        question.setWidth(frameWidth-60);
        question.setHeight(frameHeight/5);
        question.setBounds(question.getPosX(), question.getPosY(), question.getWidth(), question.getHeight());
        answersPanel.setPosX(20);
        answersPanel.setPosY(frameHeight/5);
        answersPanel.setWidth(frameWidth-60);
        answersPanel.setHeight(frameHeight-frameHeight*2/5);
        answersPanel.setBounds(answersPanel.getPosX(), answersPanel.getPosY(), answersPanel.getWidth(), answersPanel.getHeight());
        answerWidth = 150;
        answerHeight = 30;
        answersPanel.setBackground(Color.red);
        repaint();
    }
    
    public void initGame() {
        int questionAnswerGameID = (int) Math.floor(Math.random()*new QuestionAnswersGameDao().getTableSize()+1);
        QuestionAnswersGame questionAnswersGame = new QuestionAnswersGameDao().findOne(questionAnswerGameID);
        question.displayQuestion(questionAnswersGame);
        answersPanel.setAnswers(questionAnswersGame, answerWidth, answerHeight);
        answersPanel.displayAnswers();
        answersPanel.moveAnswers();
        this.getContentPane().add(question);
        this.getContentPane().add(answersPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        frameWidth = this.getBounds().width;
        frameHeight = this.getBounds().height;
        setGameDimentions();
    }//GEN-LAST:event_formComponentResized

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuestionAnswersGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuestionAnswersGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuestionAnswersGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuestionAnswersGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuestionAnswersGameFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
